
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build the Angular app
    - name: Build Angular app
      run: npm run build -- --configuration production --base-href /

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/my-portfolio  # Replace with your dist folder name
